### ISSUE TITLE
Use custom field as title

### ISSUE THREAD

**Issue by lekkas** [resin-io/pensieve#134]
`Entry title` appears to be injected in every entry. It'd be nice to be able to pick a custom field as the entry title instead.

See: https://www.flowdock.com/app/rulemotion/r-process/threads/dz3oz0WRuNRA5yeIqPW3-sR2PCL

**Comment by LucianBuzzo** [comment]
Pensieve is designed to have a key (title) for each fragment of the document. What is the reason for wanting to pick a custom field as an entry title?

**Comment by lekkas** [comment]
Quoting from the linked thread in the description

> 'Title' is the only property that does not exist in the schema and yet is asked in the form. This kind of broke my expectations on what the input form would look like, and also I'd find it very useful if I could instead use a less-generic, more meaningful field name (e.g. 'Item description')

**Comment by LucianBuzzo** [comment]
This will be resolved by https://github.com/resin-io/pensieve/issues/189

**Comment by LucianBuzzo** [comment]
This is resolved by https://github.com/resin-io/pensieve/pull/200
The first item in the schema is used as the title
