### ISSUE TITLE
Make entry titles searchable

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io/pensieve#154]

**Comment by sqweelygig** [comment]
:+1: pls can have?

**Comment by sonyagreen** [comment]
Labeled degrades-ux because existing use of scratchpad involves looking up some entries by their title. As in "Oh, yeah, this seems like `Device appears online but not updating`." 

One short-term hack would be to include the text of the title in the body `Solution` field for SEO purposes.

**Comment by LucianBuzzo** [comment]
This will be resolved by https://github.com/resin-io/pensieve/issues/189

**Comment by LucianBuzzo** [comment]
Resolved by https://github.com/resin-io/pensieve/pull/200
