### ISSUE TITLE
Editing a saved entry should probably show all schema fields (even blank ones)

### ISSUE THREAD

**Issue by lekkas** [resin-io/pensieve#158]
<img width="1121" alt="screen shot 2017-10-05 at 16 54 28" src="https://user-images.githubusercontent.com/5211478/31230849-e340a088-a9ed-11e7-8868-e1190824325d.png">

**Comment by sonyagreen** [comment]
I wanted to save a partially added entry. When I went back to edit, the non-filled-in fields are gone.

**Comment by lekkas** [comment]
Just realised the schema is missing from the issue report, but this should easy to reproduce.

**Comment by sonyagreen** [comment]
I'm calling this a blocker because we're considering mass importing the scratchpad, which means we'll want to update almost all the entries to include fields like `Versions Affected`.
