### ISSUE TITLE
User wants to re-add a deleted field

### ISSUE THREAD

**Issue by sonyagreen** [resin-io/pensieve#165]
User opens a new entry, clicks the X to remove a field (ex. "Fix Difficulty"), then wishes to add it back. There's no way to add it back. If user creates the field as a custom field (and calls it "Fix Difficulty") will it match the existing field?

**Comment by sonyagreen** [comment]
degrades-ux because expecting users to create and edit fields as information becomes available about the entry.

**Comment by LucianBuzzo** [comment]
@sonyagreen Is this resolved by showing all the schema fields to a user? https://github.com/resin-io/pensieve/pull/191 ?

**Comment by sonyagreen** [comment]
It is!
