### ISSUE TITLE
Automated commit messages might impede the audit process

### ISSUE THREAD

**Issue by lekkas** [resin-io/pensieve#173]
From @sonyagreen 

> This seems to boil down to the question if writing custom commit messages for scratchpad entries is worth the friction. @lekkas you outlined the friction, generally that a writing a commit message requires the author to spend more time with the entry than just writing it.

> If we look at GitHub's commit messages, they aren't optional, but they do auto-fill text for you. The GitHub workflow is a lot different than Pensieve -- like, you're able to add multiple files before committing. Even in the wiki you can preview before you save, and there's a cached autosave of some sort. So, this points to reducing friction while saving an entry.

> Thinking about why to bother with commit messages at all, they aren't just documenting what changed - they document why something changed. That's what I think might be valuable to capture, because the 'why' isn't obvious even from scanning diffs. That would help whomever is auditing commit logs. If that's the only benefit, then as long as it doesn't become time inefficient the auditor can figure out the 'why' commit by commit. There's one small question left - if writing a commit message serves other purposes -- like taking a minute to explain (to yourself as well as the rest of us) why you're updating an entry. Is that reflection helpful enough to be worth the friction?

> One option would be to mimic GitHub - near the save button, offering an optional field for a change note, and assume that an author will add custom text if the edit is noteworthy. If not, the entry can use the automated commit message.

> (For the scratchpad migration I think we can deal with the pain of commit messages as a one-time cost, or find a temporary way around it. I'm thinking about the features needed for daily use.)

**Comment by lekkas** [comment]
@sonyagreen 

> Thinking about why to bother with commit messages at all, they aren't just documenting what changed - they document why something changed.

This definitely is not the case in our internal Scratchpad history, where agents had the ability to add custom commit messages. I did a very quick scan of the existing history, 45% are using the automated commit message, and just by eyeballing the remaining ones I'm pretty sure that there is not even a single entry explaining the reasons why a change was made, they all describe 'what' the change was. That said, I'm not suggesting that we should consider the previous Scratchpad workflow as being set in stone, or even right, but the existing history gives a concrete understanding of how people used it when they could contribute custom commit descriptions.

I'm afraid that expecting people to describe 'why' they made a change is very vague. What exactly do you expect to get out of such a description? Do you have a specific set of 'why's that would help you as an auditor? Could these be encoded in a drop-down instead (e.g. `[meta] Reason for update`) that would also be filterable? 

> (For the scratchpad migration I think we can deal with the pain of commit messages as a one-time cost, or find a temporary way around it. I'm thinking about the features needed for daily use.)

I don't understand how you'd take this pain lightly, if I was called to migrate a batch of 10 entries and was blocked by a required commit message for every new entry/typo/intermediate save I made, I'd simply drop using the tool altogether (or give nonsensical descriptions to move forward). In any case this point is irrelevant now, because at the moment commit messages are automated. If commit meta-descriptions do get reinstated for whatever reason, I guess we'll go with the option you mention (mimicking Github) and which Lucian also considered when tackling https://github.com/resin-io/pensieve/issues/136

**Comment by sonyagreen** [comment]
After more in-person talk, the prevailing logic is that prose is way different than code because it's more easily human readable and doesn't have dependencies and the kind of trickiness that code can have. Thus, custom commit messages aren't as necessary, because it's easy to look at a prose diff and see changes.
