### ISSUE TITLE
Deployed pensieve js in S3 appears to be an older version than the current master

### ISSUE THREAD

**Issue by lekkas** [resin-io/pensieve#174]
https://resin-production-downloads.s3.amazonaws.com/pensieve/latest/pensieve.js appears to be older than the current version (e.g. searching for 'Describe your changes' should not appear after https://github.com/resin-io/pensieve/commit/3d5ecc5c170e6c05f698250b45eb053558f9ae12 )

**Comment by lekkas** [comment]
cc @LucianBuzzo

**Comment by LucianBuzzo** [comment]
You can see which version of Pensieve is running by looking up the `PENSIEVE_VERSION` in your browser console. If you are having issues with the browser cache, you can look at the scratchpad repo for a cache-busting loader:
https://github.com/resin-io/scratchpad/blob/master/index.html#L13

The currently deployed version of Pensieve as reported on the scratchpad us `2.14.0` which is correct.

<img width="554" alt="screen shot 2017-10-10 at 16 56 12" src="https://user-images.githubusercontent.com/15064535/31396846-5fbbda78-addc-11e7-9c71-b023fb10f9fc.png">

**Comment by lekkas** [comment]
@LucianBuzzo nice! Just verified that I'm running the latest version. So then I guess my question is,  wasn't the modal killed in https://github.com/resin-io/pensieve/pull/157 ?

<img width="1210" alt="screen shot 2017-10-10 at 19 09 01" src="https://user-images.githubusercontent.com/5211478/31397467-cdb7dcc2-adee-11e7-9bc2-408420f2d1c7.png">

**Comment by LucianBuzzo** [comment]
@lekkas Are you adding a new entry? Maybe I only killed it for editing entries 🤔

**Comment by lekkas** [comment]
@LucianBuzzo Correct, this is a new entry, I thought we disabled them in all 'Save' operations. Closing this issue since there's definitely no issue wrt the Pensieve deployment pipeline.
