### ISSUE TITLE
Permalink to a specific entry

### ISSUE THREAD

**Issue by imrehg** [resin-io/pensieve#182]
It sometimes helps to share a specific entry with others, but currently there's no way to have a permalink and link to an entry (at least I couldn't find)

**Comment by sonyagreen** [comment]
This is going to be incredibly important, to be able to point to a specific entry elsewhere. "If it doesn't have a URL, it doesn't exist", my granny always says.

**Comment by sonyagreen** [comment]
Realized this too is a duplicate - #153
