### ISSUE TITLE
User can't use the same commit message twice

### ISSUE THREAD

**Issue by sonyagreen** [resin-io/pensieve#184]
This may be correlation, but I [deleted an entry](https://github.com/resin-io/scratchpad/commit/24c354e84b59732c5ceb63aae9d3bb7b395f54a3#diff-e560b9cc8350266753e992490c2a4e05) with the commit message `removing test entries`, then went to delete another entry with the same commit message, and it wouldn't go through. I was able to make the entry go through when I [changed the commit message](https://github.com/resin-io/scratchpad/commit/521a28720d7b6b86cd5af1a666289b6e3e8d95d7#diff-e560b9cc8350266753e992490c2a4e05) (to `removing test entries (and testing to see if changing the commit message means it will go through`).

**Comment by sonyagreen** [comment]
I tried creating this bug in another way - instead of deleting entry, I created two entries. First entry, my commit message was `test`. When I submitted the second entry I used the same commit message and got the error `409 error making request PUT https://api.github.com/repos/resin-io/scratchpad/contents/scratchpad.yaml: "Conflict"`.

**Comment by sonyagreen** [comment]
Labeled scratchpad-blocker because users are likely to use similar commit messages.

Short term fix: harkening back to #173, I think it'd be OK to remove commit messages for creating or duplicating entries. We could add this feature back in once we have so many commits it's a pain to audit them all.

**Comment by LucianBuzzo** [comment]
I've just tested this and I was able to successfully add entries with the same commit message one after the other:
https://github.com/resin-io/pensieve/commit/8ef42b1179e6d4053b1465b082bd0b7f4c0fb210
https://github.com/resin-io/pensieve/commit/bc59327554fbd7c4b2e71aee5a2dcd2c813298bf

Looking at the commit history on the scratchpad repo it looks like you've been able to successfully create new entries using the same commit message.
https://github.com/resin-io/scratchpad/commits/master

**Comment by LucianBuzzo** [comment]
I'm going to close this issue and will re-open if it comes up again.
