### ISSUE TITLE
Pensieve sometimes overwrites entry instead of adding a new one

### ISSUE THREAD

**Issue by imrehg** [resin-io/pensieve#185]
In a pensive-powered repo, I had multiple cases, when adding a new entry effectively rewrote the old one, and thus the old entry was lost. This is highly undesirable.

**Comment by alexandrosm** [comment]
@imrehg what do you mean "the old one"? did it overwrite a specific old entry? do you have a way to replicate this?

**Comment by imrehg** [comment]
@LucianBuzzo I've seemed to have recreated this issue, not in its minimal form, but probably close enough?
Example commit created by pensieve: https://github.com/imrehg/pensievetest/commit/a2b1faca482c5cbb2b2832f2cfe1e4fa4b970fc9

Steps to reproduce:

* in the schema have multiple fields (I used at least 3 or so), and some of them are `Text` fields (seems important)
* add an entry that has content in the text field, such that it spans over multiple paragraphs 
* save it
* wait a bit, refresh the page (so the pensieve front end gets the updated database, and not to hit clonflict in the next step)
* add a new entry, where again the text field has multiple paragraphs

One strange stuff I've seen, that if I add an entry, and then add a new one right afterwards, I end up with a 409 PUT error due to Conflict, which is fixed by waiting a bit and refreshing, so pensieve fetches the latest version of the data from the repo.

Need to note too, that due to this caching, that it can also sometimes put back the previous version, seems like a different issue, related to caching : https://github.com/imrehg/pensievetest/commit/4fa1d2f6ac107b27cf0a27e8d1b92fbbc8f5b70b
This was:
* adding an entry
* follow up entry overwrote the first one
* somehow ended up that the third entry reverted previous overwrite and added the new entry, ending up with 1st and 3rd entry only...

(browser & OS are Arch Linux,  Chromium Version 62.0.3202.62 (Developer Build) (64-bit))

**Comment by LucianBuzzo** [comment]
@imrehg What do you mean by caching? Could you clarify what you think is being cached?

**Comment by imrehg** [comment]
@LucianBuzzo Github pages caching the files that it serves and/or pensieve caching the yaml file version it is working from. That's a hunch, otherwise I'm not sure why it would happen to have such things like this conflict:
![screenshot_2017-10-24_12-46-10](https://user-images.githubusercontent.com/38863/31943430-9f43d148-b8c0-11e7-9b63-3f0e83a41c14.png)
(this is pretty repeatable by trying to add two items quickly one after the other without reloading the page)

**Comment by sonyagreen** [comment]
I had this happen a while ago and opened #169 (which I've closed because this has more info).

I'd said:
I was testing to see what happened if I added an entry, then added a second entry with the same title and `GitHub issue` field. If I'm not mistaken, the new entry overrode the old entry.

You can see it by looking for the entry that says "testing to see what happens if the entry title and GH issue are the same as an existing entry".

**Comment by sonyagreen** [comment]
I changed this to `scratchpad-blocker` because the user may not notice the old entry is overwritten.

**Comment by LucianBuzzo** [comment]
@sonyagreen This is actually a separate issue to the one reported here originally. I'm going to open up a new issue that tethers together a number of problems that are being reported due to the underlying architecture of Pensieve data.

**Comment by LucianBuzzo** [comment]
@sonyagreen The issue you've described will be resolved by https://github.com/resin-io/pensieve/issues/189
