### ISSUE TITLE
Convert underlying data structure to an array

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io/pensieve#189]
## Current state
At present, the underlying data structure used in Pensieve is an object. A key-value store where the title of a document entry is the key. 
```js
{
  'Entry No.1': {
    description: 'Lorem ipsum dolor sit amet'
  },
  'Entry no.2': {
    description: 'Integer facilisis vestibulum nibh ut ornare.'
  }
}
```

### Problems
This has a number of problems:
- You can't filter/search on the entries title 
  - https://github.com/resin-io/pensieve/issues/154
- You can't easily specify the order of entries
- You can't set a custom field as a title
  - https://github.com/resin-io/pensieve/issues/134
- Creating a new entry with the same title as an existing one overwrites the existing entry
  - https://github.com/resin-io/pensieve/issues/185#issuecomment-340572922

## Proposed state
~~What I propose is that we switch the structure to an array and add a new attribute to schema objects~~, ~~`title: boolean` that can be used to specify which field is used as the entry title~~ 
### Edit: 2017-21-11

What I propose is switching the underlying data structure of the document to an array and converting the schema to an array. The first element in the schema array is used as the title field.

The new data structure would look something like this:

```js
[
  {
    label: 'Entry No.1',
    description: 'Lorem ipsum dolor sit amet'
  },
    label: 'Entry no.2',
    description: 'Integer facilisis vestibulum nibh ut ornare.'
  }
]
```

With the schema looking like this:

```js
[
  {
    name: 'title'
    type: 'Text'
  }, {
    name: 'label'
    type: 'Text'
  }, {
    name: description,
    type: 'Text'
  }
]
```

### Upgrading existing Pensieve installations
As there are a number of Pensieve installations in existence we should provide a simple upgrade path to the new format. 
- Upon loading a Pensieve that has the old format, the user will be shown a dialogue, notifying them that they are using the old data model and offering an 'update' action. 
- If they click the 'update' button the Pensieve data will be automatically transformed and committed to the repo.
  - The current title of an entry will be set as a 'title' field on the entry
  - If a 'title' field already exists then a different field name will be used
  - The new title field will be added to the schema
  - A commit message will be generated, describing the change that has happened
- At this point, visually, the page should look the same as it did before, but the underlying data structure has been updated.

**Comment by alexandrosm** [comment]
@LucianBuzzo the "title:true" thing is problematic, as it can be made true for multiple fields. We need a single place where the title field is explicitly defined.

**Comment by LucianBuzzo** [comment]
What we settled on is converting the schema to an array of objects, and using the first element in the array as the title. The conversion process will create a schema field named `title` and place it at the beginning of the schema array.
