### ISSUE TITLE
Permalink changes if title changes

### ISSUE THREAD

**Issue by sonyagreen** [resin-io/pensieve#245]
## Expected Behavior
Permalink is perma, so we can reference it elsewhere in the resinsphere.

## Actual Behavior
Permalink changes if the title is edited

## Steps to Reproduce the Problem

1. Note permalink to entry
1. Change title text
1. Note new permalink

## Specifications

- Browser:
- OS:

## References

---

Before submitting this issue, please check that this issue is not a duplicate.
If there is another issue describing the same problem please add your
information to that issue's comments.

**Comment by lurch** [comment]
Haha, I guessed at this in #235 :smiley_cat:
