### ISSUE TITLE
Not giving the required permissions just results in infinite spinner and no error

### ISSUE THREAD

**Issue by Page-** [resin-io/pensieve#259]
## Expected Behavior
If the token doesn't have the required permissions it should show an error message and ideally the extra permissions that are needed

## Actual Behavior
The loading spinner spins indefinitely

## Steps to Reproduce the Problem

1. Generate a token with no permissions
1. Login using token

## Specifications

- Browser:
- OS:

## References

---

Before submitting this issue, please check that this issue is not a duplicate.
If there is another issue describing the same problem please add your
information to that issue's comments.

**Comment by lurch** [comment]
Duplicate of #257 ?

**Comment by Page-** [comment]
I think it's a different error @lurch, although the infinite spinner part probably has the same cause
