### ISSUE TITLE
State 

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/pensieve#36]
Had a look over the code, everything looks sound 🥇 . There are some cases I thought you may want to hoist the state out of the child components, because it's managed in a few different places now, but this is something that can be fixed with a single store like redux, but that only needs to be added if things get more complex and state becomes more fragmented.

**Comment by LucianBuzzo** [comment]
With the schema edit PR https://github.com/resin-io/pensieve/pull/44 I've added `redux` and `react-redux` to help stop the state from fragmenting too much.

**Comment by LucianBuzzo** [comment]
`react-redux` is now used extensively throughout the app, so I think this can be closed
