### ISSUE TITLE
tiny things

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/pensieve#39]
- Any reason we are checking in the build dir to .git?
- As far as I know there is no diff between how create-react app handles .jsx and js files, they all run through the babel with jsx interpreter, so maybe worth just using .js.

**Comment by LucianBuzzo** [comment]
Checking in the build-dir means that we can link directly to the latest built asset on https://resin-io.github.io/scratchpad/ 
The best way to handle this kind of thing is an ongoing discussion as checking in the build dir is not an ideal solution.
Even though .jsx and .js files are treated the same, I prefer to use the .jsx extension if the file contains jsx as it is more descriptive.

**Comment by LucianBuzzo** [comment]
Now that we have continuous deployment to S3 we no longer check in the build directory.
